- debian/changelog
Zero lintain errors.
```
Now running lintian...
Finished running lintian.
```
Plus resulting package has been uploaded to mentors.debian.net
```
dput -f mentors libpoly0_1.3-2_amd64.changes
Checking signature on .changes
gpg: Signature made Thu 15 Jun 2017 04:08:29 PM GMT using RSA key ID F10CFE93
gpg: Good signature from "Ian A. Mason (My Software Signing Key) <iam@csl.sri.com>"
Good signature on /vagrant/ianamason/libpoly0_1.3-2_amd64.changes.
Checking signature on .dsc
gpg: Signature made Thu 15 Jun 2017 03:55:10 PM GMT using RSA key ID F10CFE93
gpg: Good signature from "Ian A. Mason (My Software Signing Key) <iam@csl.sri.com>"
Good signature on /vagrant/ianamason/libpoly0_1.3-2.dsc.
Package includes an .orig.tar.gz file although the debian revision suggests
that it might not be …
```
> closes itp bug.

- examples/cad/cad.py
This seems to fix a bug where the cad example says that a list does not provide the method `factor_square_free`
> fix typo in cad.py

- python/setup.py.in
This works for people who want to install polypy as a python module.
```
python setup.py install
```
> a setup.py.in that works with setuptools

- include/integer.h
- src/number/integer.c
- src/number/integer.h
This adds a const for `lp_int_ring_t*` arguments almost everywhere.
The exceptions are `lp_int_ring_attach` and `lp_int_ring_detach` which actually intend to modify the ring. Note however, that they internally (attempt to?) do a cast to a non-const pointer anyway, which seems unnecessary.
> Adding const for (almost) all lp_int_ring_t* arguments.

- src/interval/interval.c
I found that `lp_dyadic_interval_scale` does not work properly for negative `n`. This PR fixes this issue.
> Properly scale upper bound in lp_dyadic_interval_scale() for negative n.

- src/interval/interval.c
`lp_dyadic_interval_contains_zero` yields incorrect results if the upper bound happens to be zero.
Check, for example, with `(-1 ; 0)` and `(-1 ; 0]`. Also compare against the implementation of `lp_rational_interval_contains_zero`...
> Fix contains_zero check for upper bound.

- include/upolynomial.h
- include/upolynomial_factors.h
- python/polypyInteger.h
- python/polypyInteger2.c
- python/polypyInteger3.c
- python/polypyUPolynomial3.c
- python/utils.h
- python/utils2.c
- python/utils3.c
- src/upolynomial/factorization.c
- src/upolynomial/factors.c
- src/upolynomial/gcd.c
- src/upolynomial/umonomial.c
- src/upolynomial/umonomial.h
- src/upolynomial/upolynomial.c
- src/upolynomial/upolynomial_dense.c
- src/upolynomial/upolynomial_dense.h
PR #24 left some places untouched where `lp_int_ring_t*` was still used without `const`. This adds const to these remaining places, mostly concerning the univariate polynomial.
> Made usage of lp_int_ring_t* const at more places.

- include/polyxx.h
- include/polyxx/integer.h
- include/polyxx/integer_ring.h
- include/polyxx/rational.h
- src/CMakeLists.txt
- src/polyxx/integer.cpp
- src/polyxx/integer_ring.cpp
- src/polyxx/rational.cpp
- test/polyxx/CMakeLists.txt
- test/polyxx/test_integer.cpp
- test/polyxx/test_rational.cpp
Based on #25 , this PR adds new wrapper classes for `lp_integer_t` (`Integer`) and `lp_rational_t` (`Rational`). Additionally, a helper class `IntegerRing`(wrapping `lp_int_ring_t`) is added.
For `Integer`, usage with and without a custom integer ring, should be reasonably comfortable and straight forward. Both classes induce no memory overhead, which allows for easy (and fast) conversions of arrays by a simple cast.
Most of the C interface is exported in the C++ interface as well and unit tests are added.
> Adding wrapper classes for lp_integer_t and lp_rational_t

- include/polyxx.h
- include/polyxx/dyadic_interval.h
- include/polyxx/dyadic_rational.h
- src/CMakeLists.txt
- src/polyxx/dyadic_interval.cpp
- src/polyxx/dyadic_rational.cpp
- test/polyxx/CMakeLists.txt
- test/polyxx/test_dyadic_interval.cpp
- test/polyxx/test_dyadic_rational.cpp
This PR depends on #30. It adds new wrapper classes for `lp_dyadic_rational_t` (`DyadicRational`) and `lp_dyadic_interval_t` (`DyadicInterval`). Both classes induce no memory overhead, which allows for easy (and fast) conversions of arrays by a simple cast.
Most of the C interface is exported in the C++ interface as well and unit tests are added.
> Adding wrapper classes for lp_dyadic_rational_t and lp_dyadic_interval_t.

- include/polyxx/integer.h
- include/polyxx/rational.h
During further integration, it turned out that additional cases to and from `mpz_class` and `mpq_class` (like the one between the new C++ classes and the underlying C structs) are very convenient. This PR adds these casts.
> Add casts to and from mpz_class and mpq_class.

- include/polyxx.h
- include/polyxx/algebraic_number.h
- include/polyxx/upolynomial.h
- src/CMakeLists.txt
- src/polyxx/algebraic_number.cpp
- src/polyxx/upolynomial.cpp
- test/polyxx/CMakeLists.txt
- test/polyxx/test_algebraic_number.cpp
- test/polyxx/test_upolynomial.cpp
The PR adds new wrapper classes for `lp_upolynomial_t` (`UPolynomial`) and `lp_algebraic_number_t` (`AlgebraicNumber`). As for `Integer`, usage of `UPolynomial` with a custom integer ring should be reasonably comfortable.
`UPolynomial` follows the C++ api and holds the `lp_upolynomial_t` instance as a pointer (`std::unique_ptr`), and thus allows for efficient move operations.
`AlgebraicNumber` on the other hand holds the `lp_algebraic_number_t` as its only member (much like `Integer` and `Rational`) and thus allows for easy casting to and from `lp_algebraic_number_t`.
Most of the C interface is exported in the C++ interface as well and unit tests are added.
> Adding wrapper classes for lp_upolynomial_t and lp_algebraic_number_t

- src/number/value.c
Right now, `LP_VALUE_NONE` is handled in `lp_value_cmp` in a somewhat unexpected way.
While comparison of two none values or of a none value with (plus or minus) infinity works fine, comparison with a number type fails with an assertion (that does not even give a reason, but just `assert(0);`).
This PR handles `LP_VALUE_NONE` as yet another sentinel value that is considered the smallest of all values, even below `LP_VALUE_MINUS_INFINITY`.
> Handle none as a special lower-than-everything-else value in value comparison

- include/polyxx/utils.h
- src/CMakeLists.txt
- src/polyxx/algebraic_number.cpp
- src/polyxx/dyadic_interval.cpp
- src/polyxx/dyadic_rational.cpp
- src/polyxx/integer.cpp
- src/polyxx/integer_ring.cpp
- src/polyxx/rational.cpp
- src/polyxx/upolynomial.cpp
- src/polyxx/utils.cpp
I noticed that the previous pattern to implement `operator<<()` for the C++ wrapper classes leads to leaking memory in many cases. This PR fixes this issue.
> Fixed memory leaks in streaming operators within C++ wrapper.

- .travis.yml
- scripts/osx.deps.sh
- scripts/ubuntu.deps.sh
I found that travis jobs took way longer on macos because brew packages were being updated.
As I have not found a particularly good reason for this, this PR removes that and performs some general cleanup on the travis setup.
> Improve setup times on travis, make scripts consistent for ubuntu and osx

- src/interval/interval.c
Fixes #45.
This PR refactors both `lp_dyadic_interval_set_a` and `lp_interval_set_a` to support point intervals. Essentially, it moves the special case for `I->is_point` to the front and thereby avoid the immediate comparison with `&I->b` (which segfaults, because `b` is not initialized).
> Fix lp_interval_set_a (and lp_dyadic_interval_set_a) when I is a point interval.

- src/number/value.c
This PR fixes a few (somewhat) recently introduced issues that make compilation fail due to `-Werror`.
While the initialization should not change anything, the missing `break` might actually lead to incorrect behavior.
> Avoid unintended fall-through, ensure proper initialization.

- src/CMakeLists.txt
The current cmake setup contains a safeguard that prevents having explicit `-fPIC` enabled builds if the current platform is known to have `-fPIC` by default anyway.
This makes using libpoly in an automated way more difficult than necessary: assume we want to build it in a platform-agnostic way and only build the thing we need (static with `-fPIC`), we currently need to replicate this logic and compile either `static_poly` or `static_pic_poly` and then link against either `libpoly.a` or `libpicpoly.a` (or instead manually move `libpicpoly.a` to `libpoly.a`).
The only benefits of this safeguard seem to be to (a) avoid the overhead of compilation if we do not need `-fPIC` and run `make [all]` and (b) possibly make the user aware of this issue.
This PR weakens this mechanism and instead sets …
> Allow -fPIC build on all platforms

- src/polyxx/dyadic_interval.cpp
- src/polyxx/interval.cpp
- src/polyxx/interval_assignment.cpp
This PR fixes a subtle memory leak in certain assignment and move assignment constructors in the C++ wrapper.
We sometimes construct a new object over the existing object without destructing the existing object beforehand.
> Fix memory leak in C++ wrapper

- src/CMakeLists.txt
I'm just fixing up the Nix package for `libpoly` on darwin and am finding I need to make this change to prevent 0.1.9's build failing with
```
CMake Error at src/CMakeLists.txt:73 (add_library):
Cannot find source file:
utils/open_memstream.c utils/debug_trace.c
```
Full log: https://nix-cache.s3.amazonaws.com/log/r4y0c1mgrj3h0dbxscfawxf2nqww923q-libpoly-0.1.9.drv
With the quoting in place it appears to be failing to interpret `utils/open_memstream.c` and `utils/debug_trace.c` as two separate entries.
This is on macos 10.15 with cmake 3.19.7.
> CMakeLists.txt: de-quote conditional appending of open_memstream.c

- src/number/algebraic_number.c
- test/polyxx/test_algebraic_number.cpp
This PR fixes `lp_algebraic_number_neg`: the method crashes when the algebraic number that is to be negated is actually rational (i.e. has no defining polynomial). Further down the method calls `lp_algebraic_number_construct` which assumes the polynomial to be non-null.
This PR introduces a proper special case, similar to `lp_algebraic_number_inv`.
> Fix issue with lp_algebraic_number_neg when number is actually rational

- include/polyxx/algebraic_number.h
- src/polyxx/algebraic_number.cpp
- test/polyxx/test_algebraic_number.cpp
This PR adds `operator/()` and `inverse()` for the C++ wrapper class `AlgebraicNumber`.
> Add operator/() and inverse() for the C++ wrapper AlgebraicNumber()

- src/number/algebraic_number.c
- test/polyxx/test_algebraic_number.cpp
Sometimes `lp_algebraic_number_is_rational` would correctly identify that an algebraic number is in fact rational, but `lp_algebraic_number_to_rational` would fail to return this exact rational. This happens when the algebraic number has a defining polynomial, but the isolating interval is a point interval or the polynomial is only linear.
This PR fixes this issue by implementing these cases in `lp_algebraic_number_to_rational`.
Now, whenever `lp_algebraic_number_is_rational` returns true, `lp_algebraic_number_to_rational` should produce the exact rational value.
> Improve lp_algebraic_number_to_rational

- include/algebraic_number.h
- include/upolynomial.h
- python/polypyAlgebraicNumber.h
- python/polypyAlgebraicNumber2.c
- python/polypyAlgebraicNumber3.c
- src/interval/arithmetic.c
- src/interval/arithmetic.h
- src/number/algebraic_number.c
- src/number/dyadic_rational.h
- src/upolynomial/upolynomial.c
- test/python/tests/algebraic_number.py
I mainly wanted to understand how the library was built, so the approach is surely very naive. But I though it was sad that the algebraic numbers only provide operations that the rational provides. So this MR adds an implementation of the positive root of a positive algebraic number.
> Add positive root function of two algebraic numbers

- test/polyxx/doctest.h
This fixes build on PPC.
Mirrors my submission to Macports: https://github.com/macports/macports-ports/pull/14980
> libpoly: fix doctest.h to allow PPC build

- src/CMakeLists.txt
- src/interval/interval.c
- src/number/algebraic_number.c
- src/number/dyadic_rational.h
- src/number/integer.c
- src/number/integer.h
- src/number/rational.h
- src/number/value.c
- src/polynomial/feasibility_set.c
- src/polynomial/output.c
- src/upolynomial/output.c
- src/utils/assignment.c
- src/utils/u_memstream.c
- src/utils/u_memstream.h
- src/variable/variable_order.c
- test/polyxx/test_algebraic_number.cpp
- test/polyxx/test_assignment.cpp
- test/polyxx/test_dyadic_interval.cpp
- test/polyxx/test_dyadic_rational.cpp
- test/polyxx/test_integer.cpp
- test/polyxx/test_interval.cpp
- test/polyxx/test_interval_assignment.cpp
- test/polyxx/test_polynomial.cpp
- test/polyxx/test_rational.cpp
- test/polyxx/test_rational_interval.cpp
- test/polyxx/test_upolynomial.cpp
- test/polyxx/test_value.cpp
- test/polyxx/test_variable.cpp
`u_memstream` is an `open_memstream`-like API that is designed to work universally across multiple operating systems, including Windows. These changes finally allow using the various `*_to_string` functions on Windows without segfaulting, thereby fixing #65.
I have added some basic `polyxx` test cases involving the `<<` operator, which is defined in terms of the `*_to_string` functions, to ensure that the bug that this patch fixes remains fixed.
> Adapt `u_memstream` code from `mesa`

- src/upolynomial/factorization.c
This variable triggers `-Wunused-but-set-variable` warnings with Clang 15 or later, causing the build to fail due to `-Werror`.
Fixes #67.
> Remove unused `enabled_count` variable

- python/polypyPolynomial3.c
- python/polypyValue3.c
- python/polypyVariable3.c
Fixes https://github.com/SRI-CSL/libpoly/issues/70.  The `Py_hash_t` type may or may not be the same size as long, and is definitely not the same size on i386 Linux and FreeBSD.
> Use Py_hash_t as return type of hash functions

- include/poly.h
- include/polynomial_hash_set.h
- include/polynomial_heap.h
- include/polynomial_vector.h
- include/upolynomial.h
- include/variable_order.h
- python/polypyPolynomial3.c
- src/CMakeLists.txt
- src/polynomial/polynomial_hash_set.c
- src/polynomial/polynomial_heap.c
- src/polynomial/polynomial_vector.c
- src/upolynomial/upolynomial.c
Added lp_polynomial_heap and some additional functions for hash_set and vector (e.g., move functions), and some minor fixes
> Data structures update

- debian/libpoly0.symbols
- include/integer.h
- include/polyxx/upolynomial.h
- include/upolynomial.h
- python/polypyUPolynomial3.c
- src/CMakeLists.txt
- src/number/integer.h
- src/polynomial/polynomial.c
- src/polyxx/upolynomial.cpp
- src/upolynomial/factorization.c
- src/upolynomial/factorization.h
- src/upolynomial/root_finding.c
- src/upolynomial/root_finding.h
- src/upolynomial/upolynomial.c
- src/upolynomial/upolynomial.h
- src/upolynomial/upolynomial_vector.c
- src/upolynomial/upolynomial_vector.h
- test/polyxx/test_upolynomial.cpp
- test/python/tests/upolynomial_roots.py
Implemented rabin root finding for polynomials in Zp
> Rabin root finding

- include/feasibility_set.h
- include/integer.h
- include/interval.h
- include/polyxx/interval.h
- python/polypyFeasibilitySet2.c
- python/polypyFeasibilitySet3.c
- python/polypyInterval2.c
- python/polypyInterval3.c
- src/interval/interval.c
- src/number/integer.c
- src/number/integer.h
- src/number/value.c
- src/polynomial/feasibility_set.c
- src/polyxx/interval.cpp
- src/upolynomial/factorization.c
- src/upolynomial/root_finding.c
- test/polyxx/test_interval.cpp
This PR adds support for query the number of integers in a feasible set.
> Integer handling for feasible sets
